config/routes.rb
Csas::Application.routes.draw do

  resources :profiles
  resources :assistants
  resources :events
  resources :contents
  get "/constitution" => 'welcome#constitution', as: :constitution
  patch 'players/:id/request' => 'players#propose', as: :request_campaign_participation
  patch 'players/:id/accept' => 'players#accept', as: :accept_campaign_request
  patch 'players/:id/reject' => 'players#reject', as: :reject_campaign_request
  patch 'players/:id/remove' => 'players#remove', as: :remove_campaign_participation

  patch 'events/:id/attach_campaign' => "events#attach_campaign", as: :attach_campaign_to_event
  patch 'campaigns/:id/attach_event' => "campaigns#attach_event", as: :attach_event_to_campaign

  resources :players

  resources :campaigns
  patch 'campaigns/:id/add_pc' => 'campaigns#add_pc', as: :add_pc
  patch 'campaigns/:id/remove_pc' => 'campaigns#remove_pc', as: :remove_pc
  patch 'campaigns/:id/complete' => 'campaigns#complete', as: :complete_campaign
  resources :player_characters
  resources :characters
  patch 'player_characters/:id/kill_player_character' => 'player_characters#kill', as: :kill_player_character
  patch 'player_characters/:id/retire_player_character' => 'player_characters#retire', as: :retire_player_character
  patch 'player_characters/:id/lose_player_character' => 'player_characters#lose', as: :lose_player_character
  patch 'player_characters/:id/player_character_quit' => 'player_characters#quit', as: :player_character_quit
  patch 'player_characters/:id/player_character_join' => 'player_characters#join', as: :player_character_join
  patch 'player_characters/:id/resurrect_player_character' => 'player_characters#resurrect', as: :resurrect_player_character
  patch 'player_characters/:id/find_player_character' => 'player_characters#find', as: :find_player_character

  patch 'characters/:id/clone_character' => 'character#clone', as: :clone_character

  resources :journal_entries
  resources :resources
  resources :attachments
  resources :games
  resources :versions
  resources :newsletters
  resources :emails
  root 'welcome#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  

end

app/models/journal_entry.rb
# == Schema Information
#
# Table name: journal_entries
#
#  id                  :integer          not null, primary key
#  content             :text
#  date                :string(255)
#  player_character_id :integer
#  private             :boolean          default(FALSE)
#  created_at          :datetime
#  updated_at          :datetime
#

class JournalEntry < ActiveRecord::Base
  validates_presence_of :content, :date, :player_character
  belongs_to :player_character
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  load_and_authorize_resource param_method: :journal_entry_params

  def index
    @journal_entries = JournalEntry.all
  end

  def new
    @journal_entry = JournalEntry.new
  end

  def create
    @journal_entry = JournalEntry.new(journal_entry_params)
    if @journal_entry.save
      if request.referrer.match('journal_entries')
        redirect_to @journal_entry, :notice  => "Successfully add journal_entry."
      else
        redirect_to request.referrer, :notice  => "Successfully add journal_entry."
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @journal_entry = JournalEntry.find(params[:id])
  end

  def update
    @journal_entry = JournalEntry.find(params[:id])
    if @journal_entry.update_attributes(journal_entry_params)
      redirect_to @journal_entry, :notice  => "Successfully updated journal entry."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.destroy
    redirect_to journal_entry_url, :notice => "Successfully destroyed Journal Entry."
  end

  def show
    @journal_entry = JournalEntry.find(params[:id])
  end

  private

  def journal_entry_params
    params.require(:journal_entry).permit(:content, :date, :player_character_id)
  end
end

app/views/journal_entries/_form.html.haml
-# Below is to allow this form to be used by other controller as renders
- journal_entry = @journal_entry if @journal_entry.present?
= form_for journal_entry do |f|
  = f.error_messages
  %p
    = f.label :date
    = f.text_field :date
  %p
    = f.label :content
    = f.text_area :content
  - if defined?(player_character) && player_character.present?
    = f.hidden_field :player_character_id, value: player_character.id
  -else
    %p
      = f.label :player_character
      = f.collection_select :player_character_id, PlayerCharacter.all, :id, :id,  include_blank: "Please Select"
  %p
    = f.submit

app/views/journal_entries/_journal_entry_summary_box.html.haml
.summary_box
  = "Character: #{journal_entry.player_character.name}"
  %br
  = "Date: #{journal_entry.date}"
  %br
  Content:
  %br
  = journal_entry.content.truncate(150)
  %br
  = link_to "View Full Entry", journal_entry_path(journal_entry)

app/views/journal_entries/edit.html.haml
- title "Edit Journal Entry"

= render 'form'

%p
  = link_to "Show", @journal_entry
  |
  = link_to "View All", journal_entry_path

app/views/journal_entries/index.html.haml
- title "Journal Entires"
- if can? :create, JournalEntry
  - edit_text "Create New Journal Entry"
  - edit_path new_journal_entry_path

%section
  .section_header
    %h2 Listing
  .section_content
    = render partial: "journal_entry_summary_box", collection: @journal_entries, as: "journal_entry"

app/views/journal_entries/new.html.haml
- title "New Journal Entry"

= render 'form'

%p= link_to "Back to List", journal_entries_path

app/views/journal_entries/show.html.haml
- title "#{@journal_entry.player_character.name} #{@journal_entry.date}"
- if can? :update, @journal_entry
  - edit_text "Edit Journal Entry"
  - edit_path edit_journal_entry_path(@journal_entry)

%section{id: "main"}
  #main_info
    = markdown(@journal_entry.content)
    %p= "Written By: #{link_to @journal_entry.player_character.name, player_character_path(@journal_entry.player_character)}".html_safe