config/routes.rb
Csas::Application.routes.draw do

  resources :profiles
  resources :assistants
  resources :events
  resources :contents
  get "/constitution" => 'welcome#constitution', as: :constitution
  patch 'players/:id/request' => 'players#propose', as: :request_campaign_participation
  patch 'players/:id/accept' => 'players#accept', as: :accept_campaign_request
  patch 'players/:id/reject' => 'players#reject', as: :reject_campaign_request
  patch 'players/:id/remove' => 'players#remove', as: :remove_campaign_participation

  patch 'events/:id/attach_campaign' => "events#attach_campaign", as: :attach_campaign_to_event
  patch 'campaigns/:id/attach_event' => "campaigns#attach_event", as: :attach_event_to_campaign

  resources :players

  resources :campaigns
  patch 'campaigns/:id/add_pc' => 'campaigns#add_pc', as: :add_pc
  patch 'campaigns/:id/remove_pc' => 'campaigns#remove_pc', as: :remove_pc
  patch 'campaigns/:id/complete' => 'campaigns#complete', as: :complete_campaign
  resources :player_characters
  resources :characters
  patch 'player_characters/:id/kill_player_character' => 'player_characters#kill', as: :kill_player_character
  patch 'player_characters/:id/retire_player_character' => 'player_characters#retire', as: :retire_player_character
  patch 'player_characters/:id/lose_player_character' => 'player_characters#lose', as: :lose_player_character
  patch 'player_characters/:id/player_character_quit' => 'player_characters#quit', as: :player_character_quit
  patch 'player_characters/:id/player_character_join' => 'player_characters#join', as: :player_character_join
  patch 'player_characters/:id/resurrect_player_character' => 'player_characters#resurrect', as: :resurrect_player_character
  patch 'player_characters/:id/find_player_character' => 'player_characters#find', as: :find_player_character

  patch 'characters/:id/clone_character' => 'character#clone', as: :clone_character

  resources :journal_entries
  resources :resources
  resources :attachments
  resources :games
  resources :versions
  resources :newsletters
  resources :emails
  root 'welcome#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :player
  belongs_to :player_character
  belongs_to :image, class_name: "Resource"
  has_many :attachments, as: :attachable
  has_many :resources, through: :attachments

  has_many :journal_entries

  #validates :player, :presence => true
  validates :campaign, :presence => true

  alias_attribute :title, :name

  include AASM

  aasm :column => 'status' do
    state :adventuring, inital: true
    state :retired
    state :dead
    state :missing
    state :gone

    event :join do
      transitions from: [:retired, :dead, :missing], to: :adventuring
    end

    event :retire do
      transitions from: [:adventuring, :missing], to: :retired
    end

    event :kill do
      transitions from: [:adventuring, :missing], to: :dead
    end

    event :lose do
      transitions from: :adventuring, to: :missing
    end

    event :quit do
      transitions from: :adventuring, to: :gone
    end

  end


end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  load_and_authorize_resource param_method: :character_params

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
    @possible_images = Resource.where('file_content_type like ?', '%image%')
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      if request.referrer.match('characters')
        redirect_to @character, :notice  => "Successfully add character to the campaign."
      else
        redirect_to request.referrer, :notice  => "Successfully add character to the campaign."
      end
    else
      if request.referrer.match('characters')
        flash['alert'] = "Failed to add character to this campaign."
        render "new"
      else
        redirect_to request.referrer, :notice  => "Unable to add character to the campaign."
      end
    end
  end

  def edit
    @character = Character.find(params[:id])
    @possible_images = Resource.where('file_content_type like ?', '%image%')
    if @character.image present?
      @possible_images = @possible_images - [@character.image]
    end
  end

  def update
    @character = Character.find(params[:id])
    params["character"] = params["character"].except("image_id") if params["character"]["image_id"].blank?
    if @character.update_attributes(character_params)
      redirect_to @character, :notice  => "Successfully updated PC."
    else
      render :action => 'edit'
    end
  end

  def show
    @character = Character.find(params[:id])
    @new_attachment = Attachment.new
    @attachments = @character.attachments
    @possible_resources = Resource.all
    @attachments.each do  |attachment|
      @possible_resources  = @possible_resources  - [attachment.resource]
    end
    @possible_resources
  end

  def destroy
    @character = Character.find(params[:id])
    if @characters.destroy
      redirect_to campaign_path(@characters.campaign.id), :notice  => "Removed character to this campaign."
    else
      redirect_to campaign_path(@characters.campaign.id), :notice  => "Failed to remove character to this campaign."
    end
  end

  #Figure out how to dry this up. Maybe one action with a argument.
  def join
    @character = Character.find(params[:id])
    return_to =  Rails.application.routes.recognize_path(request.referrer)[:controller] == "characters" ? @character : request.referrer
    if @character.join!
      redirect_to return_to, notice: "Character is now adventuring in this campaign"
    else
      flash[:alert] = "Unable to proccess"
      render 'show'
    end
  end

  def retire
    @character = Character.find(params[:id])
    return_to =  Rails.application.routes.recognize_path(request.referrer)[:controller] == "characters" ? @character : request.referrer
    if @character.retire!
      redirect_to return_to, notice: "Character is now retired"
    else
      flash[:alert] = "Unable to proccess "
      render 'show'
    end
  end

  def kill
    @character = Character.find(params[:id])
    return_to =  Rails.application.routes.recognize_path(request.referrer)[:controller] == "characters" ? @character : request.referrer
    if @character.kill!
      redirect_to return_to, notice: "Character is now dead"
    else
      flash[:alert] = "Unable to proccess "
      render 'show'
    end
  end

  def lose
    @character = Character.find(params[:id])
    return_to =  Rails.application.routes.recognize_path(request.referrer)[:controller] == "characters" ? @character : request.referrer
    if @character.lose!
      redirect_to return_to, notice: "Character is now missing"
    else
      flash[:alert] = "Unable to proccess "
      render 'show'
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :caste, :campaign_id, :description, :bio, :secrets, :player_id, :character_id, :image_id, :status)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def avaliable_campaigns(user)
    Campaign.references(:players).includes(:players).where("players.user_id = ?", user.id)
  end
end

app/views/characters/_attach_to_campaign.html.haml
= form_tag(find_pc(character.id), method: :patch) do
  = label_tag :campaign
  = select_tag(:campaign, options_from_collection_for_select(avaliable_campaigns(current_user), :id, :title))
  = submit_tag("Add")

app/views/characters/_form.html.erb
<%- player_character = @player_character if defined?(@player_character)%>
<%= form_for player_character do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :caste, value: "Class" %>
    <%= f.text_field :caste %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </p>
  <p>
    <%= f.label :secrets %>
    <%= f.text_area :secrets %>
  </p>
  <%- if player_character.new_record? %>
    <%- if defined?(campaign_id) %>
      <p>
        <%= f.hidden_field :campaign_id, value: campaign_id %>
      </p>
    <%- else %>
      <p>
        <%= f.label :campaign %>
        <%= f.collection_select :campaign_id, current_user.campaigns, :id, :title, prompt: true %>
      </p>
    <%- end %>
    <%- if defined?(player_id)%>
      <p>
        <%= f.hidden_field :player_id, value: player_id %>
      </p>
    <%- else %>
      <p>
        <%= f.label :player %>
        <%= f.collection_select :player_id, current_user.players, :id, :display_name, prompt: true %>
      </p>
    <%- end %>
  <%- end %>
  <p>
    <%= f.label :image %>
    <%= f.collection_select :image_id, possible_images(player_character), :id, :file_file_name, include_blank: "Please Select" , required: false%>
    <%= link_to("Current Image: #{player_character.image.file_file_name}", player_character.image.file.url )if player_character.image.present? %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/characters/_pc.html.haml
.summary_box
  = "Character Name: #{pc.name}"
  %br
  = "Player:  #{pc.player.display_name}"
  %br
  = "Class: #{pc.caste}"
  %br
  = "Status: #{pc.status}"
  %br
  = link_to "View Charcter Info", player_character_path(pc)

app/views/characters/_status_actions.html.erb
<%- if current_user == pc.campaign.gm || current_user == pc.player.user%>
  <%if ["dead", "missing", "retired"].include?(pc.status)%>
    <%= form_for pc, url: join_pc_path(pc) do |f| %>
      <%= f.submit value: "Re-Add Character to Campaign" %>
    <%end%>
  <% else %>
    <%= form_for pc, url: kill_pc_path(pc) do |f| %>
      <%= f.submit value: "Set Character to dead" %>
    <%end%>
    <%= form_for pc, url: retire_pc_path(pc) do |f| %>
      <%= f.submit value: "Set character retired" %>
    <%end%>
    <%= form_for pc, url: lose_pc_path(pc) do |f| %>
      <%= f.submit value: "Set character to MIA" %>
    <%end%>
  <%end%>
<% else %>
  No action avaliable
<% end %>

app/views/characters/edit.html.erb
<% title "Edit Player Charcter" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @player_character%> |
  <%= link_to "View All", player_character_path %>
</p>

app/views/characters/index.html.erb
<% title "Player Characters" %>
<% if can? :create, PlayerCharacter %>
  <% edit_text "Create New Player" %>
  <% edit_path new_player_character_path %>
<%end%>

<section>
  <div class="section_header">
    <h2>Listing</h2>
  </div>
  <div class="section_content">
    <%= render partial: "pc.html.haml", collection: @player_characters, as: "pc" %>
  </div>
</section>

app/views/characters/new.html.erb
<% title "New Player Character" %>

<%= render 'form' %>

<p><%= link_to "Back to List", player_characters_path %></p>

app/views/characters/show.html.erb
<% title @player_character.name %>
<% if can? :update, @player_character %>
  <% edit_text "Edit PC" %>
  <% edit_path edit_player_character_path(@player_character) %>
<%end%>

<section id="main">
  <div id="main_image">
    <%-if @player_character.image.present? %>
      <%= image_tag @player_character.image.file.url(:medium) %>
    <%-end%>
  </div>
  <div class="main_info">
    <p>
      <strong>Description:</strong>
      <%= markdown(@player_character.description) if @player_character.description %>
    </p>
    <p>
      <strong>Bio:</strong>
      <%= markdown(@player_character.bio) if @player_character.bio %>
    </p>
    <p>
      <strong>Secrets:</strong>
      <%= markdown(@player_character.secrets) if @player_character.secrets %>
    </p>

    <p>
      <strong>Campaign:</strong>
      <%= link_to @player_character.campaign.title, campaign_path(@player_character.campaign) %>
    </p>
    <p>
    <strong>Player:</strong>
      <%= @player_character.player.display_name %>
      </p>
    <p
    <p>
    <strong>Status:</strong>
      <%= @player_character.status.humanize%>
    </p>

    <p>
      <strong>Game:</strong>
      <%= link_to @player_character.campaign.game.title,  @player_character.campaign.game %>
    </p>

    <p>
      <strong>GM:</strong>
      <%= @player_character.campaign.gm.display_name %>
    </p>


    <p>
      <%= link_to "View All", campaigns_path %>
    </p>
  </div>

  <%= render partial: "status_actions", :locals => {:pc => @player_character} %>
</section>
<% unless @player_character.attachments.empty? && cannot?(:update, @player_character) %>
<section class="attachments">
  <div class="section_header">
    <h2> Attachemnts </h2>
    <% if can? :update, @player_character %>
      <%= content_tag :a, "Attach File", :href => "#attach_to", :class => 'btn add_action_link', :data => {:toggle => 'modal'} %>
    <%- end %>
  </div>
  <div class="section_content">
    <%= render partial: "attachments/attached", collection: @player_character.attachments, as: "attachment" %>
  </div>
</section>
<%end%>
<% unless @player_character.attachments.empty? && cannot?(:update, @player_character) %>
  <%= atttachment_form(@player_character) -%>
<%- end %>


<section>
  <div class="section_header">
    <h2>Journal Entries</h2>
    <% if current_user == @player_character.player.user%>
      <%= content_tag :a, "Add Journal Entry", :href => "#add_journal_entry", :class => 'btn add_action_link', :data => {:toggle => 'modal'} %>
    <% end %>

  </div>
  <div class="section_content">
    <%= render partial: "journal_entries/journal_entry_summary_box", collection: @player_character.journal_entries, as: "journal_entry" %>
  </div>
</section>

<%if current_user == @player_character.player.user %>
  <%= modal_dialog :id => "add_journal_entry",
    :header => { :show_close => true, :dismiss => 'modal', :title => "Add Journal Entry to #{@player_character.name}" },
    :body => render(partial: "journal_entries/form", locals: {player_character: @player_character, journal_entry: JournalEntry.new}),
    :footer =>  content_tag(:button, 'Cancel', :class => 'btn btn-primary', :data => { :dismiss => 'modal' })
  %>
<%-end%>