config/routes.rb
Csas::Application.routes.draw do

  resources :profiles
  resources :assistants
  resources :events
  resources :contents
  get "/constitution" => 'welcome#constitution', as: :constitution
  patch 'players/:id/request' => 'players#propose', as: :request_campaign_participation
  patch 'players/:id/accept' => 'players#accept', as: :accept_campaign_request
  patch 'players/:id/reject' => 'players#reject', as: :reject_campaign_request
  patch 'players/:id/remove' => 'players#remove', as: :remove_campaign_participation

  patch 'events/:id/attach_campaign' => "events#attach_campaign", as: :attach_campaign_to_event
  patch 'campaigns/:id/attach_event' => "campaigns#attach_event", as: :attach_event_to_campaign

  resources :players

  resources :campaigns
  patch 'campaigns/:id/add_pc' => 'campaigns#add_pc', as: :add_pc
  patch 'campaigns/:id/remove_pc' => 'campaigns#remove_pc', as: :remove_pc
  patch 'campaigns/:id/complete' => 'campaigns#complete', as: :complete_campaign
  resources :player_characters
  resources :characters
  patch 'player_characters/:id/kill_player_character' => 'player_characters#kill', as: :kill_player_character
  patch 'player_characters/:id/retire_player_character' => 'player_characters#retire', as: :retire_player_character
  patch 'player_characters/:id/lose_player_character' => 'player_characters#lose', as: :lose_player_character
  patch 'player_characters/:id/player_character_quit' => 'player_characters#quit', as: :player_character_quit
  patch 'player_characters/:id/player_character_join' => 'player_characters#join', as: :player_character_join
  patch 'player_characters/:id/resurrect_player_character' => 'player_characters#resurrect', as: :resurrect_player_character
  patch 'player_characters/:id/find_player_character' => 'player_characters#find', as: :find_player_character

  patch 'characters/:id/clone_character' => 'character#clone', as: :clone_character

  resources :journal_entries
  resources :resources
  resources :attachments
  resources :games
  resources :versions
  resources :newsletters
  resources :emails
  root 'welcome#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  

end

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/resources/_resource_summary_box.html.haml
.summary_box
  = "File Name:  #{resource.file_file_name.truncate(20)}"
  %br
  = "File Type: #{resource.file_content_type}"
  %br
  = "File Size #{number_to_human_size(resource.file_file_size)}"
  %br
  = link_to "View Attachment Info", resource_path(resource)
  %br
  = link_to "Download or Open File", resource.file.url

app/views/resources/edit.html.erb
<% title "Edit Resource" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @resource %> |
  <%= link_to "View All", resources_path %>
</p>

app/views/resources/index.html.erb
<% title "Resources" %>
<% if can? :create, Resource %>
  <% edit_text "Upload New Resource" %>
  <% edit_path new_resource_path %>
<%end%>

<section>
  <div class="section_header">
    <h2>Listing</h2>
  </div>
  <div class="section_content">
    <%= render partial: "resource_summary_box", collection: @resources, as: "resource" %>
  </div>
</section>

app/views/resources/new.html.erb
<% title "New Resource" %>

<%= render 'form' %>

<p><%= link_to "Back to List", resources_path %></p>

app/views/resources/show.html.erb
<% title "Resource" %>
<% if can? :update, @resource %>
  <% edit_text "Edit Resource" %>
  <% edit_path edit_resource_path(@resource) %>
<%end%>

<section>
  <%- if @resource.file_content_type == 'image/jpeg' %>
    <%= image_tag @resource.file.url(:medium) %>
  <%-end%>
  <br>
  <strong>Name:</strong>
  <%= @resource.file_file_name %>
  <br>
  <strong>Type:</strong>
  <%= @resource.file_content_type %>
</section>