config/routes.rb
Csas::Application.routes.draw do

  resources :profiles
  resources :assistants
  resources :events
  resources :contents
  get "/constitution" => 'welcome#constitution', as: :constitution
  patch 'players/:id/request' => 'players#propose', as: :request_campaign_participation
  patch 'players/:id/accept' => 'players#accept', as: :accept_campaign_request
  patch 'players/:id/reject' => 'players#reject', as: :reject_campaign_request
  patch 'players/:id/remove' => 'players#remove', as: :remove_campaign_participation

  patch 'events/:id/attach_campaign' => "events#attach_campaign", as: :attach_campaign_to_event
  patch 'campaigns/:id/attach_event' => "campaigns#attach_event", as: :attach_event_to_campaign

  resources :players

  resources :campaigns
  patch 'campaigns/:id/add_pc' => 'campaigns#add_pc', as: :add_pc
  patch 'campaigns/:id/remove_pc' => 'campaigns#remove_pc', as: :remove_pc
  patch 'campaigns/:id/complete' => 'campaigns#complete', as: :complete_campaign
  resources :player_characters
  resources :characters
  patch 'player_characters/:id/kill_player_character' => 'player_characters#kill', as: :kill_player_character
  patch 'player_characters/:id/retire_player_character' => 'player_characters#retire', as: :retire_player_character
  patch 'player_characters/:id/lose_player_character' => 'player_characters#lose', as: :lose_player_character
  patch 'player_characters/:id/player_character_quit' => 'player_characters#quit', as: :player_character_quit
  patch 'player_characters/:id/player_character_join' => 'player_characters#join', as: :player_character_join
  patch 'player_characters/:id/resurrect_player_character' => 'player_characters#resurrect', as: :resurrect_player_character
  patch 'player_characters/:id/find_player_character' => 'player_characters#find', as: :find_player_character

  patch 'characters/:id/clone_character' => 'character#clone', as: :clone_character

  resources :journal_entries
  resources :resources
  resources :attachments
  resources :games
  resources :versions
  resources :newsletters
  resources :emails
  root 'welcome#index'

  devise_for :users, controllers: { registrations: "users/registrations" }

  

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                 :integer          not null, primary key
#  campaign_id        :integer
#  user_id            :integer
#  aasm_state         :string(255)
#  status_approver_id :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :campaign
  belongs_to :status_approver, class_name: 'User'

  has_many :player_characters

  validate :user, presence: true
  validate :status_approver, presence: true

  delegate :display_name, to: :user

  include AASM

  alias_attribute :status, :aasm_state

  aasm do
    state :pending, :initial => true
    state :active
    state :removed
    state :denied

    event :activate do
      transitions :from => :pending, :to => :active,  :guard => :check_auth_active, :on_transition => Proc.new {|obj, *args| obj.set_status_approver(*args) }
    end

    event :deny do
      transitions :from => :pending, :to => :denied,  :guard => :check_auth_denied, :on_transition => Proc.new {|obj, *args| obj.set_status_approver(*args) }
    end

    event :remove do
      transitions :from => :active, :to => :removed, :on_transition => Proc.new {|obj, *args| obj.set_status_approver(*args) }
    end

    event :request do
      transitions :from => [:denied, :removed], :to => :pending,  :guard => :check_auth_pending, :on_transition => Proc.new {|obj, *args| obj.set_status_approver(*args) }
    end
  end

  def check_auth_active(user)
    if user == self.campaign.gm
      return true
    else
      return (self.status_approver_id.nil? || self.status_approver != user) ? true : false
    end
  end

  def check_auth_denied(user)
    if user == self.campaign.gm
      return true
    else
      return (self.status_approver_id.nil? || self.status_approver != user) ? true : false
    end
  end

  def check_auth_pending(user)
    if user == self.campaign.gm
      return true
    else
      return (self.status_approver_id.nil? || self.status_approver == user) ? true : false
    end
  end

  def set_status_approver(user)
    self.status_approver = user
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.status_approver = current_user
    return_to = Rails.application.routes.recognize_path(request.referrer)[:controller] == "players" ? @player : request.referrer
    respond_to do |format|
      if @player.save
        if current_user == @player.campaign.gm && @player.user != current_user
          CampaignAccess.delay.invite_player(@player.campaign, @player.user)
        elsif current_user = @player.user && @player.campaign.gm != current_user
          CampaignAccess.delay.request_access(@player.campaign, @player.user)
        end
        format.html { redirect_to return_to, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: "Player now pending" }
      format.json { head :no_content }
    end
  end

  def accept
    @player = Player.find(params[:id])
    authorize! :update, @player
    return_to = Rails.application.routes.recognize_path(request.referrer)[:controller] == "players" ? @player : request.referrer
    @player.activate(:active, current_user)
    if @player.save
      redirect_to return_to, notice: "Player now active"
    else
      flash[:alert] = "Updable to approve this request"
      render 'show'
    end
  end

  def reject
    @player = Player.find(params[:id])
    authorize! :update, @player
    return_to = Rails.application.routes.recognize_path(request.referrer)[:controller] == "players" ? @player : request.referrer
    @player.deny(:denied, current_user)
    if @player.save
      redirect_to return_to, notice: "Player now rejected"
    else
      flash[:alert] = "Updable to reject this request"
      render 'show'
    end
  end

  def remove
    @player = Player.find(params[:id])
    authorize! :update, @player
    return_to = Rails.application.routes.recognize_path(request.referrer)[:controller] == "players" ? @player : request.referrer
    @player.remove(:removed, current_user)
    if @player.save
      redirect_to return_to, notice: "Player now removed"
    else
      render 'show'
    end
  end

  def propose
    @player = Player.find(params[:id])
    authorize! :update, @player
    return_to = Rails.application.routes.recognize_path(request.referrer)[:controller] == "players" ? @player : request.referrer
    @player.request(:pending, current_user)
    if @player.save
      redirect_to return_to, notice: "Player now pending"
    else
      flash[:alert] = "Updable to reject this request"
      render 'show'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:campaign_id, :user_id, :status, :status_approved_by)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :campaign_id %><br>
    <%= f.collection_select :campaign_id, Campaign.all, :id, :title, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.confirmed, :id, :email, prompt: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_player_summary_box.html.haml
-if player.present?
  .summary_box{ id: "player_#{player.id}"}
    = "Player Name: #{player.user.display_name}" if player.user.present?
    %br
    = "Status: #{player.status}"
    %br
    = "Joined Campaign: #{distance_of_time_in_words(player.created_at, Time.now)} ago"
    - if current_user.present?
      %br
      .action{id: "player_#{player.id}_actions"}
        = render partial: "/players/status_actions", :locals => {:player => player}

app/views/players/_status_actions.html.erb
<%- if current_user == player.campaign.gm || current_user == player.user%>
  <%if player.status == "pending" %>
    <%if player.status_approver == current_user && player.user != player.campaign.gm  %>
      <p>Awaiting responce</p>
    <%else%>
      <%= form_for player, url: accept_campaign_request_path(player) do |f| %>
        <%= f.submit value: "Accept Request" %>
      <%end%>
      <%= form_for player, url: reject_campaign_request_path(player) do |f| %>
        <%= f.submit value: "Reject Request" %>
      <%end%>

    <%end%>
  <%end%>


  <%if player.status == "active"%>
      <%= form_for player, url: remove_campaign_participation_path(player) do |f| %>
        <%= f.submit value: (current_user == player.user ? "Leave Campaign" : "Remove Player from Campaing")%>
      <%end%>
  <%end%>

  <%if player.status == "denied" && player.user == current_user%>
    <%if player.status_approver == current_user %>
      <%= form_for player, url: request_campaign_participation_path(player) do |f| %>
        <%= f.submit value: "Re-Request Access" %>
      <%end%>
    <%else%>
      <p>The GM rejected your request to join this campaign and will need to re-invite you to change the status<p>
    <%end%>
  <%end%>

  <%if player.status == "denied" && player.user != current_user%>
    <%if player.status_approver != current_user %>
      <p>User rejected the invite to this campaign and will need to amke a new request to change the status</p>
    <%else%>
      <%= form_for player, url: request_campaign_participation_path(player) do |f| %>
        <%= f.submit value: "Re-Invite Player" %>
      <%end%>
    <%end%>
  <%end%>

  <%if player.status == "removed" && player.user == current_user%>
    <%if player.status_approver == current_user %>
      <%= form_for player, url: request_campaign_participation_path(player) do |f| %>
        <%= f.submit value: "Re-Request Access" %>
      <%end%>
    <%else%>
      <p>The GM removed you from this campaign and will need to re-invite you to change the status<p>
    <%end%>
  <%end%>

  <%if player.status == "removed" && player.user != current_user%>
    <%if player.status_approver != current_user %>
      <p>User removed them self from this campaign and will need to amke a new request to change the status</p>
    <%else%>
      <%= form_for player, url: request_campaign_participation_path(player) do |f| %>
        <%= f.submit value: "Re-Invite Player"%>
      <%end%>

    <%end%>
  <%end%>
<%else%>
  No action Available
<%end%>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<% title "Players" %>
<% if can? :create, Player %>
  <% edit_text "Create New Player" %>
  <% edit_path new_player_path %>
<%end%>

<section>
  <div class="section_header">
    <h2>Listing</h2>
  </div>
  <div class="section_content">
    <%= render partial: "player_summary_box", collection: @players, as: "player" %>
  </div>
</section>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @player.campaign.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @player.user.display_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @player.status %>
</p>



<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>
<h2>Button for Changing Status</h2>
<%if @player.status == "pending" && @player.user == current_user%>
  <%if @player.status_approver == current_user %>
    <p>Awaiting responce</p>
  <%else%>
    <%= form_for @player, url: accept_campaign_request_path do |f| %>
      <%= f.submit value: "Accept Request"  %>
    <%end%>
    <%= form_for @player, url: reject_campaign_request_path do |f| %>
      <%= f.submit value: "Reject Request"  %>
    <%end%>
  <%end%>
<%end%>

<%= render partial: "status_actions", :locals => {:player => @player} %>